SELECT NAME, OPEN_MODE FROM V$PDBS;

CREATE PLUGGABLE DATABASE PDBORCL
ADMIN USER pdbadmin IDENTIFIED BY Password123
ROLES = (DBA)
FILE_NAME_CONVERT = ('/opt/oracle/oradata/XE/pdbseed/', '/opt/oracle/oradata/XE/PDBORCL/');

ALTER PLUGGABLE DATABASE PDBORCL OPEN;

ALTER SESSION SET CONTAINER = PDBORCL;
SELECT NAME FROM V$CONTAINERS WHERE CON_ID = SYS_CONTEXT('USERENV','CON_ID');

CREATE TABLESPACE USERS 
DATAFILE '/opt/oracle/oradata/XE/PDBORCL/users01.dbf' 
SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER VAV IDENTIFIED BY Password123
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO VAV;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM, CREATE DATABASE LINK TO VAV;
GRANT RESTRICTED SESSION TO VAV;



CREATE USER NAN IDENTIFIED BY Password123
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO NAN;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM, CREATE DATABASE LINK TO NAN;
GRANT RESTRICTED SESSION TO NAN;

CREATE USER LPV IDENTIFIED BY Password123
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO LPV;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM, CREATE DATABASE LINK TO LPV;
GRANT RESTRICTED SESSION TO LPV;

ALTER SESSION SET CONTAINER = CDB$ROOT;



CREATE TABLE employees (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    salary NUMBER(10,2)
);

CREATE TABLE departments (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100) NOT NULL 
);

DELETE FROM employees;

INSERT INTO employees (id, name, salary) VALUES (1, 'Alice', 5000);
INSERT INTO employees (id, name, salary) VALUES (2, 'Bob', 6000);

INSERT INTO departments (id, name) VALUES (1, 'IT');
INSERT INTO departments (id, name) VALUES (2, 'HR');

COMMIT;

SELECT * FROM employees;


CREATE DATABASE LINK NAN_db 
   CONNECT TO NAN
   IDENTIFIED BY "12345"
   USING '26.255.29.148:1521/PDBORCL';

SELECT * FROM city@NAN_db;

CREATE DATABASE LINK LPV_db 
   CONNECT TO LPV
   IDENTIFIED BY "Password123"
   USING '26.28.197.103:1521/PDBORCL';
   
SELECT * FROM buns@LPV_db;


SET SERVEROUTPUT on;


-- Распределенные транзакции

-- INSERT/INSERT


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN
    INSERT INTO city@NAN_db (a, city) VALUES (4, 'Brest');
    INSERT INTO employees (id, name, salary) VALUES (3, 'Alice', 5000);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLERRM);
END;

SELECT * FROM city@NAN_db;
SELECT * FROM employees;


-- INSERT/UPDATE

BEGIN
    INSERT INTO city@NAN_db (a, city) VALUES (5, 'Pinsk');
    UPDATE employees SET name = 'Обновлённые данные' WHERE id = 1;


    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLERRM);
END;

SELECT * FROM city@NAN_db;
SELECT * FROM employees;

-- UPDATE/INSERT

BEGIN
    UPDATE city@NAN_db SET city = 'Обновлённые данные' WHERE a = 1;
    INSERT INTO employees (id, name, salary) VALUES (8, 'Alice', 5000);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLERRM);
END;

SELECT * FROM city@NAN_db;
SELECT * FROM employees;


-- Нарушение целостности

BEGIN
    INSERT INTO city@NAN_db (a, city) VALUES (5, 'Pinsk');
    INSERT INTO employees (id, name, salary) VALUES (10, 'Alice', 5000);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Ошибка: ' || SQLERRM);
END;

SELECT * FROM city@NAN_db;
SELECT * FROM employees;


-- Пример задержки ресурса


SELECT * FROM city@NAN_db;
SELECT * FROM employees;


INSERT INTO employees (id, name, salary) VALUES (5, 'Bob', 5000);

COMMIT;

ROLLBACK;

DELETE FROM employees WHERE id = 5;

COMMIT;